---
title: "Individual Spillover effect -- Reliability Analysis"
output: html_document
date: "2025-06-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list=ls())
```


```{r Libraries, warning=FALSE, message=FALSE}
# Set locale to English
Sys.setlocale("LC_ALL", "en_US.UTF-8")

#!/usr/bin/env Rscript
library(ggplot2)
library(boot)
library(readr)
library(tidyr)
library(dplyr)
library(stringr)
library(readr)
library(gridExtra)
library(lme4)
library(lmerTest)
library(MASS)
library(brms)
library(rstan)
library(cmdstanr)
```


We recommend to run these models on a cluster. Each model, especially the geco and indico ones can take more than 2 weeks to run!

# PoTec -- cross domain reliability
```{r Read Potec Data}
measures_col <- c("gaze_duration", "first_fixation", "total_duration", "go_past_time", "FPReg", "skip", "FPSkip")

# read data
potec <- read.csv("../data/potec/potec_expertise.csv", header=TRUE) %>% 
  dplyr::select(PP_ID, trial, text_id_numeric, text_domain_numeric, reader_discipline_numeric, word_index_in_text, word_with_punct, all_of(measures_col), surp, word_len_punct, zipf_freq) %>% 
  rename(subj = PP_ID,  text = text_id_numeric, text_domain = text_domain_numeric, reader_discipline = reader_discipline_numeric, word_id = word_index_in_text, word = word_with_punct, len = word_len_punct, freq = zipf_freq) %>%
  mutate(
    subj_id = as.integer(factor(subj))
  ) %>%
  group_by(subj_id, trial, text) %>%
  arrange(word_id, .by_group = TRUE) %>%
  mutate(
    prev_len = lag(len),
    prev_freq = lag(freq),
    prev_surp = lag(surp)
  ) %>%
  ungroup() %>%
  filter(surp > 0, prev_surp > 0) %>%
  # mutate(
  #   freq = ifelse(freq == 0, 1, freq),
  #   prev_freq = ifelse(prev_freq == 0, 1, prev_freq)) %>%
  mutate(
    len = as.numeric(scale(len)),
    freq = as.numeric(scale(freq)),
    surp = as.numeric(scale(surp)),
    prev_len = as.numeric(scale(prev_len)),
    prev_freq = as.numeric(scale(prev_freq)),
    prev_surp = as.numeric(scale(prev_surp))
  ) %>%
  mutate(
    subj = paste0("s", subj),
    text = paste0("t", text)
  ) %>%
  pivot_longer(cols = all_of(measures_col), names_to = "measures", values_to = "value") %>%
  group_by(measures) %>%
  mutate(
    mean = mean(value, na.rm = TRUE),
    sd = sd(value, na.rm = TRUE)
  ) %>%
  filter((measures %in% c("FPReg","FPSkip","skip")) | value <= (mean + 5 * sd)) %>%
  ungroup() %>%
  dplyr::select(-mean, -sd) %>%
  mutate(
    c1 = ifelse(text_domain == reader_discipline, 1, 0), # expert reading 
    c2 = ifelse(text_domain != reader_discipline, 1, 0)  # non-expert reading
  ) %>%
  drop_na()

# View(potec)

# write_csv(potec, "../data/fit_input/potec.csv")
```


```{r Model Potec Gaze Duration}
# set priors
priors_rt <- c(
  prior(normal(5.5, 0.1), class = Intercept),
  prior(normal(0, 0.1), class = b),
  prior(exponential(2), class = sd),
  prior(exponential(2), class = sigma),
  prior(lkj(2), class = cor)
)

for(mes in c("gaze_duration")) {
  print(paste0("Fitting model for ", mes))
  
  temp_df <- potec %>%
    filter(measures == mes) %>%
    filter(value > 0)
  
  # Fit the model for RT measures
  model <- brms::brm(
    value ~ 1 + c2 + len + freq + surp + prev_len + prev_freq + prev_surp + 
    (0 + c1 + c2 + (len + freq + surp + prev_len + prev_freq + prev_surp):c1 + (len + freq + surp + prev_len + prev_freq + prev_surp):c2 | subj_id),
    data = temp_df,
    chains = 4,
    family = lognormal(link = 'identity'),
    warmup = 1000,
    iter = 2000,
    file = paste0("../models/cor_scaled/", "potec_", mes),
    cores = 4,
    backend = "cmdstan",
    silent = 0,
    prior = priors_rt
  )
}

print("Done fitting models")
```


# OneStop -- cross regime reliability
```{r Read OneStop Data}
measures_col <- c("gaze_duration", "first_fixation", "total_duration", "go_past_time", "FPReg", "skip", "FPSkip")

# read data
onestop <- read.csv("../data/onestop/onestop_repeat.csv", header=TRUE) %>% 
  dplyr::select(PP_ID, TRIAL_INDEX, article_id, paragraph_id, repeated_reading_trial, IA_ID, IA_LABEL, all_of(measures_col), word_len_punct, zipf_freq, surp) %>% 
  rename(subj = PP_ID,  trial = TRIAL_INDEX, text = article_id, paragraph = paragraph_id, word_id = IA_ID, word = IA_LABEL, len = word_len_punct, freq = zipf_freq) %>% 
  mutate(
    subj_id = as.integer(factor(subj)),
    trial = as.integer(trial),
    text = as.integer(text),
    paragraph = as.integer(paragraph)
  ) %>%
  mutate(across(all_of(measures_col), ~ as.numeric(ifelse(. == ".", "0", .)))) %>%
  mutate(across(all_of(measures_col), ~ as.numeric(.))) %>%
  group_by(subj_id, trial, text, paragraph) %>%
  arrange(word_id, .by_group = TRUE) %>%
  mutate(
    prev_len = lag(len),
    prev_freq = lag(freq),
    prev_surp = lag(surp)
  ) %>%
  ungroup() %>%
  # filter(freq > 0, prev_freq > 0, surp > 0, prev_surp > 0) %>%
  mutate(
    len = as.numeric(scale(len)),
    freq = as.numeric(scale(freq)),
    surp = as.numeric(scale(surp)),
    prev_len = as.numeric(scale(prev_len)),
    prev_freq = as.numeric(scale(prev_freq)),
    prev_surp = as.numeric(scale(prev_surp))
  ) %>%
  mutate(
    # subj = paste0("s", subj),
    text = paste0("t", text),
    repeated = ifelse(repeated_reading_trial == "TRUE", 1, 0)
  ) %>%
  pivot_longer(cols = all_of(measures_col), names_to = "measures", values_to = "value") %>%
  group_by(measures) %>%
  mutate(
    mean = mean(value, na.rm = TRUE),
    sd = sd(value, na.rm = TRUE)
  ) %>%
  filter((measures %in% c("FPReg", "skip", "FPSkip")) | value <= (mean + 5 * sd)) %>%
  ungroup() %>%
  dplyr::select(-mean, -sd) %>%
  mutate(
    c1 = ifelse(repeated == 1, 1, 0), #  repeated reading
    c2 = ifelse(repeated == 0, 1, 0)  # normal reading
  ) %>%
  drop_na()

# View(onestop)
# write_csv(onestop, "../data/fit_input/onestop.csv")

```

```{r Model OneStop Gaze Duration}
# set priors
priors_rt <- c(
  prior(normal(5.1, 0.1), class = Intercept),
  prior(normal(0, 0.1), class = b),
  prior(exponential(2), class = sd),
  prior(exponential(2), class = sigma),
  prior(lkj(1), class = cor)
)

for(mes in c("gaze_duration")) {
  print(paste0("Fitting model for ", mes))
  
  temp_df <- onestop %>%
    filter(measures == mes) %>%
    filter(value > 0)
  
  # Fit the model for RT measures
  model <- brms::brm(
    value ~ 1 + c2 + len + freq + surp + prev_len + prev_freq + prev_surp + 
    (0 + c1 + c2 + (len + freq + surp + prev_len + prev_freq + prev_surp):c1 + (len + freq + surp + prev_len + prev_freq + prev_surp):c2 | subj_id),
    data = temp_df,
    chains = 4,
    family = lognormal(),
    warmup = 1000,
    iter = 2000,
    file = paste0("../models/cor_scaled/", "onestop_", mes),
    cores = 4,
    backend = "cmdstan",
    silent = 0,
    prior = priors_rt
  )
}

print("Done fitting models")
```

# HKC -- cross scope reliability
```{r Read HKC Data}
measures_col <- c("gaze_duration", "first_fixation", "total_duration", "FPReg", "skip", "FPSkip")

hkc_sent <- read.csv("../data/hkc/hkc_sent.csv", header = TRUE) %>% 
  dplyr::select(PP_ID, TRIAL_INDEX, para_or_sent_id, IA_ID, IA_LABEL, Format, all_of(measures_col), word_len_punct, zipf_freq, surp) %>% 
  rename(subj = PP_ID,  trial = TRIAL_INDEX, text = para_or_sent_id, word_id = IA_ID, word = IA_LABEL, format=Format, len = word_len_punct, freq = zipf_freq) %>% 
  mutate(
    subj_id = as.integer(factor(subj)),
    trial = as.integer(trial),
    text = as.integer(text),
    word_id = as.integer(word_id)
  ) %>%
  mutate(across(all_of(measures_col), ~ as.numeric(ifelse(. == ".", "0", .)))) %>%
  mutate(across(all_of(measures_col), ~ as.numeric(.))) %>%
  group_by(subj_id, trial, text) %>%
  arrange(word_id, .by_group = TRUE) %>%
  mutate(
    prev_len = lag(len),
    prev_freq = lag(freq),
    prev_surp = lag(surp)
  ) %>%
  ungroup() %>%
  filter(freq > 0, prev_freq > 0, surp > 0, prev_surp > 0) %>%
  mutate(
    len = as.numeric(scale(len)),
    freq = as.numeric(scale(freq)),
    surp = as.numeric(scale(surp)),
    prev_len = as.numeric(scale(prev_len)),
    prev_freq = as.numeric(scale(prev_freq)),
    prev_surp = as.numeric(scale(prev_surp))
  ) %>%
  mutate(
    subj = paste0("s", subj),
    text = paste0("t", text)
  ) %>% 
  pivot_longer(cols = all_of(measures_col), names_to = "measures", values_to = "value") %>%
  group_by(measures) %>%
  mutate(
    mean = mean(value, na.rm = TRUE),
    sd = sd(value, na.rm = TRUE)
  ) %>%
  filter((measures %in% c("FPReg", "skip", "FPSkip")) | value <= (mean + 5 * sd)) %>%
  ungroup() %>%
  dplyr::select(-mean, -sd)

hkc_para <- read.csv("../data/hkc/hkc_para.csv", header = TRUE) %>% 
  separate(WORD_ID, into = c("w1", "trial", "w3"), sep = "-", remove = FALSE) %>%
  mutate(trial = as.integer(trial)) %>%
  dplyr::select(PP_ID, trial, para_or_sent_id, IA_ID, IA_LABEL, FORMAT, all_of(measures_col), word_len_punct, zipf_freq, surp) %>% 
  rename(subj = PP_ID, text=para_or_sent_id, word_id = IA_ID, word = IA_LABEL, format=FORMAT, len = word_len_punct, freq = zipf_freq) %>% 
  mutate(
    subj_id = as.integer(factor(subj)),
    trial = as.integer(trial),
    text = as.integer(text),
    word_id = as.integer(word_id)
  ) %>%
  mutate(across(all_of(measures_col), ~ as.numeric(ifelse(. == ".", "0", .)))) %>%
  mutate(across(all_of(measures_col), ~ as.numeric(.))) %>%
  group_by(subj_id, trial, text) %>%
  arrange(word_id, .by_group = TRUE) %>%
  mutate(
    prev_len = lag(len),
    prev_freq = lag(freq),
    prev_surp = lag(surp)
  ) %>%
  ungroup() %>%
  filter(freq > 0, prev_freq > 0, surp > 0, prev_surp > 0) %>%
  mutate(
    len = as.numeric(scale(len)),
    freq = as.numeric(scale(freq)),
    surp = as.numeric(scale(surp)),
    prev_len = as.numeric(scale(prev_len)),
    prev_freq = as.numeric(scale(prev_freq)),
    prev_surp = as.numeric(scale(prev_surp))
  ) %>%
  mutate(
    subj = paste0("s", subj),
    text = paste0("t", text)
  ) %>%
  pivot_longer(cols = all_of(measures_col), names_to = "measures", values_to = "value") %>%
  group_by(measures) %>%
  mutate(
    mean = mean(value, na.rm = TRUE),
    sd = sd(value, na.rm = TRUE)
  ) %>%
  filter((measures %in% c("FPReg", "skip", "FPSkip")) | value <= (mean + 5 * sd)) %>%
  ungroup() %>%
  dplyr::select(-mean, -sd)

hkc_para_sent <- rbind(hkc_sent, hkc_para)

hkc <- hkc_para_sent %>%
  mutate(
    c1 = ifelse(format == "P", 1, 0), #  paragraph reading
    c2 = ifelse(format == "S", 1, 0)  # sentence reading
  ) %>%
  drop_na()

# View(hkc)
# write_csv(hkc, "../data/fit_input/hkc.csv")
```

```{r Model HKC Gaze Duration}
# set priors
priors_rt <- c(
  prior(normal(5.3, 0.1), class = Intercept),
  prior(normal(0, 0.05), class = b),
  prior(exponential(2), class = sd),
  prior(exponential(2), class = sigma),
  prior(lkj(1), class = cor)
)

for(mes in c("gaze_duration")) {
  print(paste0("Fitting model for ", mes))
  
  temp_df <- hkc %>%
    filter(measures == mes) %>%
    filter(value > 0)
  
  # Fit the model for RT measures
  model <- brms::brm(
    value ~ 1 + c2 + len + freq + surp + prev_len + prev_freq + prev_surp + 
    (0 + c1 + c2 + (len + freq + surp + prev_len + prev_freq + prev_surp):c1 + (len + freq + surp + prev_len + prev_freq + prev_surp):c2 | subj_id),
    data = temp_df,
    chains = 4,
    family = lognormal(link = "identity"),
    warmup = 1000,
    iter = 2000,
    file = paste0("../models/cor_scaled/", "hkc_converge_", mes),
    cores = 4,
    backend = "cmdstan",
    silent = 0,
    prior = priors_rt
  )
}

print("Done fitting models")
```


# GECO-ZH -- cross L1L2 reliability
```{r Read GECO-ZH Data}
measures_col <- c("gaze_duration", "first_fixation", "total_duration", "go_past_time", "FPReg", "skip", "FPSkip")

gecozhzh <- read.csv("../data/geco-zh/geco_zh_l1zh.csv", header = TRUE) %>% 
  separate(WORD_ID, into = c("part", "w2", "word_id"), sep = "-", remove = FALSE) %>% 
  mutate(word_id = as.integer(word_id)) %>%
  dplyr::select(PP_ID, part, TRIAL, word_id, IA_LABEL, LANGUAGE, all_of(measures_col), word_len_punct, zipf_freq, surp) %>% 
  rename(subj = PP_ID,  trial = TRIAL, word = IA_LABEL, lang = LANGUAGE, len = word_len_punct, freq = zipf_freq) %>% 
  mutate(
    subj_id = as.integer(factor(subj)),
    part = as.integer(part),
    trial = as.integer(trial)
  ) %>%
  mutate(across(all_of(measures_col), ~ as.numeric(ifelse(. == ".", "0", .)))) %>%
  mutate(across(all_of(measures_col), ~ as.numeric(.))) %>%
  group_by(subj_id, part, trial) %>%
  arrange(word_id, .by_group = TRUE) %>%
  mutate(
    prev_len = lag(len),
    prev_freq = lag(freq),
    prev_surp = lag(surp)
  ) %>%
  ungroup() %>%
  filter(freq > 0, prev_freq > 0, surp > 0, prev_surp > 0) %>%
  mutate(
    len = as.numeric(scale(len)),
    freq = as.numeric(scale(freq)),
    surp = as.numeric(scale(surp)),
    prev_len = as.numeric(scale(prev_len)),
    prev_freq = as.numeric(scale(prev_freq)),
    prev_surp = as.numeric(scale(prev_surp))
  ) %>%
  mutate(
    subj = paste0("s", subj)
  ) %>% 
  pivot_longer(cols = all_of(measures_col), names_to = "measures", values_to = "value") %>%
  group_by(measures) %>%
  mutate(
    mean = mean(value, na.rm = TRUE),
    sd = sd(value, na.rm = TRUE)
  ) %>%
  filter((measures %in% c("FPReg", "skip", "FPSkip")) | value <= (mean + 5 * sd)) %>%
  ungroup() %>%
  dplyr::select(-mean, -sd)

gecozhen <- read.csv("../data/geco-zh/geco_zh_l2en.csv", header = TRUE) %>% 
  separate(WORD_ID, into = c("part", "w2", "word_id"), sep = "-", remove = FALSE) %>% 
  mutate(word_id = as.integer(word_id)) %>%
  dplyr::select(PP_ID, part, TRIAL, word_id, IA_LABEL, LANGUAGE, all_of(measures_col), word_len_punct, zipf_freq, surp) %>% 
  rename(subj = PP_ID,  trial = TRIAL, word = IA_LABEL, lang = LANGUAGE, len = word_len_punct, freq = zipf_freq) %>% 
  mutate(
    subj_id = as.integer(factor(subj)),
    part = as.integer(part),
    trial = as.integer(trial)
  ) %>%
  mutate(across(all_of(measures_col), ~ as.numeric(ifelse(. == ".", "0", .)))) %>%
  mutate(across(all_of(measures_col), ~ as.numeric(.))) %>%
  group_by(subj_id, part, trial) %>%
  arrange(word_id, .by_group = TRUE) %>%
  mutate(
    prev_len = lag(len),
    prev_freq = lag(freq),
    prev_surp = lag(surp)
  ) %>%
  ungroup() %>%
  filter(freq > 0, prev_freq > 0, surp > 0, prev_surp > 0) %>%
  mutate(
    len = as.numeric(scale(len)),
    freq = as.numeric(scale(freq)),
    surp = as.numeric(scale(surp)),
    prev_len = as.numeric(scale(prev_len)),
    prev_freq = as.numeric(scale(prev_freq)),
    prev_surp = as.numeric(scale(prev_surp))
  ) %>%
  mutate(
    subj = paste0("s", subj)
  ) %>%
  pivot_longer(cols = all_of(measures_col), names_to = "measures", values_to = "value") %>%
  group_by(measures) %>%
  mutate(
    mean = mean(value, na.rm = TRUE),
    sd = sd(value, na.rm = TRUE)
  ) %>%
  filter((measures %in% c("FPReg", "skip", "FPSkip")) | value <= (mean + 5 * sd)) %>%
  ungroup() %>%
  dplyr::select(-mean, -sd)

gecozh_l1l2 <- rbind(gecozhzh, gecozhen)

gecozh <- gecozh_l1l2 %>%
  mutate(
    c1 = ifelse(lang == "Chinese", 1, 0), #  L1 Chinese reading
    c2 = ifelse(lang == "English", 1, 0)  # L2 English reading
  ) %>%
  # filter(freq > 0, prev_freq > 0, surp > 0, prev_surp > 0) %>%
  drop_na()

# View(gecozh)
# write_csv(gecozh, "../data/fit_input/gecozh.csv")
```

```{r}
# set priors
priors_rt <- c(
  prior(normal(5.5, 0.1), class = Intercept),
  prior(normal(0, 0.1), class = b),
  prior(exponential(2), class = sd),
  prior(exponential(2), class = sigma),
  prior(lkj(2), class = cor)
)

for(mes in c("gaze_duration")) {
  print(paste0("Fitting model for ", mes))
  
  temp_df <- gecozh %>%
    filter(measures == mes) %>%
    filter(value > 0)
  
  # Fit the model for RT measures
  model <- brms::brm(
    value ~ 1 + c2 + len + freq + surp + prev_len + prev_freq + prev_surp +
    (0 + c1 + c2 + (len + freq + surp + prev_len + prev_freq + prev_surp):c1 + (len + freq + surp + prev_len + prev_freq + prev_surp):c2 | subj_id),
    data = temp_df,
    chains = 4,
    family = lognormal(),
    warmup = 1000,
    iter = 2000,
    file = paste0("../models/cor_scaled/", "gecozh_", mes),
    cores = 4,
    backend = "rstan",
    silent = 0,
    prior = priors_rt
  )
}

print("Done fitting models")
```


# GECO-NL -- cross L1L2 reliability
```{r Read GECO-NL Data}
measures_col <- c("gaze_duration", "first_fixation", "total_duration", "go_past_time", "FPReg", "skip", "FPSkip")

geconlnl <- read.csv("../data/geco-nl/geco_nl_l1nl.csv", header = TRUE) %>% 
  separate(WORD_ID, into = c("part", "w2", "word_id"), sep = "-", remove = FALSE) %>% 
  mutate(word_id = as.integer(word_id)) %>%
  dplyr::select(PP_NR, part, TRIAL, word_id, IA_LABEL, LANGUAGE, all_of(measures_col), word_len_punct, zipf_freq, surp) %>% 
  rename(subj = PP_NR,  trial = TRIAL, word = IA_LABEL, lang = LANGUAGE, len = word_len_punct, freq = zipf_freq) %>% 
  mutate(
    subj_id = as.integer(factor(subj)),
    part = as.integer(part),
    trial = as.integer(trial)
  ) %>%
  mutate(across(all_of(measures_col), ~ as.numeric(ifelse(. == ".", "0", .)))) %>%
  mutate(across(all_of(measures_col), ~ as.numeric(.))) %>%
  group_by(subj_id, part, trial) %>%
  arrange(word_id, .by_group = TRUE) %>%
  mutate(
    prev_len = lag(len),
    prev_freq = lag(freq),
    prev_surp = lag(surp)
  ) %>%
  ungroup() %>%
  filter(freq > 0, prev_freq > 0, surp > 0, prev_surp > 0) %>%
  mutate(
    len = as.numeric(scale(len)),
    freq = as.numeric(scale(freq)),
    surp = as.numeric(scale(surp)),
    prev_len = as.numeric(scale(prev_len)),
    prev_freq = as.numeric(scale(prev_freq)),
    prev_surp = as.numeric(scale(prev_surp))
  ) %>%
  mutate(
    subj = paste0("s", subj)
  ) %>% 
  pivot_longer(cols = all_of(measures_col), names_to = "measures", values_to = "value") %>%
  group_by(measures) %>%
  mutate(
    mean = mean(value, na.rm = TRUE),
    sd = sd(value, na.rm = TRUE)
  ) %>%
  filter((measures %in% c("FPReg", "skip", "FPSkip")) | value <= (mean + 5 * sd)) %>%
  ungroup() %>%
  dplyr::select(-mean, -sd)

geconlen <- read.csv("../data/geco-nl/geco_nl_l2en.csv", header = TRUE) %>% 
  separate(WORD_ID, into = c("part", "w2", "word_id"), sep = "-", remove = FALSE) %>% 
  mutate(word_id = as.integer(word_id)) %>%
  dplyr::select(PP_NR, part, TRIAL, word_id, IA_LABEL, LANGUAGE, all_of(measures_col), word_len_punct, zipf_freq, surp) %>% 
  rename(subj = PP_NR,  trial = TRIAL, word = IA_LABEL, lang = LANGUAGE, len = word_len_punct, freq = zipf_freq) %>% 
  mutate(
    subj_id = as.integer(factor(subj)),
    part = as.integer(part),
    trial = as.integer(trial)
  ) %>%
  mutate(across(all_of(measures_col), ~ as.numeric(ifelse(. == ".", "0", .)))) %>%
  mutate(across(all_of(measures_col), ~ as.numeric(.))) %>%
  group_by(subj_id, part, trial) %>%
  arrange(word_id, .by_group = TRUE) %>%
  mutate(
    prev_len = lag(len),
    prev_freq = lag(freq),
    prev_surp = lag(surp)
  ) %>%
  ungroup() %>%
  filter(freq > 0, prev_freq > 0, surp > 0, prev_surp > 0) %>%
  mutate(
    len = as.numeric(scale(len)),
    freq = as.numeric(scale(freq)),
    surp = as.numeric(scale(surp)),
    prev_len = as.numeric(scale(prev_len)),
    prev_freq = as.numeric(scale(prev_freq)),
    prev_surp = as.numeric(scale(prev_surp))
  ) %>%
  mutate(
    subj = paste0("s", subj)
  ) %>% 
  pivot_longer(cols = all_of(measures_col), names_to = "measures", values_to = "value") %>%
  group_by(measures) %>%
  mutate(
    mean = mean(value, na.rm = TRUE),
    sd = sd(value, na.rm = TRUE)
  ) %>%
  filter((measures %in% c("FPReg", "skip","FPSkip")) | value <= (mean + 5 * sd)) %>%
  ungroup() %>%
  dplyr::select(-mean, -sd)

geconl_l1l2 <- rbind(geconlnl, geconlen)

geconl <- geconl_l1l2 %>%
  mutate(
    c1 = ifelse(lang == "Dutch", 1, 0), #  L1 Dutch reading
    c2 = ifelse(lang == "English", 1, 0)  # L2 English reading
  ) %>%
  # filter(freq > 0, prev_freq > 0, surp > 0, prev_surp > 0) %>%
  drop_na()

# write_csv(geconl, "../data/fit_input/geconl.csv")

```

```{r Model GECO-NL Data}
for(mes in c("gaze_duration")) {
  print(paste0("Fitting model for ", mes))
  
  temp_df <- geconl %>%
    filter(measures == mes) %>%
    filter(value > 0)
  
  # Fit the model for RT measures
  model <- brms::brm(
    value ~ 1 + c2 + len + freq + surp + prev_len + prev_freq + prev_surp + 
    (0 + c1 + c2 + (len + freq + surp + prev_len + prev_freq + prev_surp):c1 + (len + freq + surp + prev_len + prev_freq + prev_surp):c2 | subj_id),
    data = temp_df,
    chains = 4,
    family = lognormal(), 
    warmup = 1000,
    iter = 2000,
    file = paste0("../models/cor_scaled/", "geconl_", mes),
    cores = 4,
    backend = "rstan",
    silent = 0,
    prior = priors_rt
  )
}

print("Done fitting models")
```


## Indico-cross session
```{r Prepare InDiCo Data}
measures_col <- c("gaze_duration", "first_fixation", "total_duration", "go_past_time", "FPReg", "skip", "FPSkip")

et_indico <- read.csv("../data/indico/indico_et.csv") %>%
  ## The Potsdam data need to be checked, we used the Zurich part
  filter(str_starts(subj_id, "zh")) %>%
  mutate(word_id = as.integer(word_id), FPSkip = ifelse(FPRT == 0, 1, 0), skip = ifelse(TFT == 0, 1, 0)) %>%
  dplyr::select(subj_id, text_id, screen_id, session_label, word_id, word, FPRT, FD, TFT, RPD_inc, FPReg, FPSkip, skip, word_length, word_length_word_n_minus_1, lex_freq, lex_freq_word_n_minus_1, surprisal, surprisal_word_n_minus_1) %>%
  rename(subj = subj_id,  trial = screen_id, gaze_duration = FPRT, first_fixation = FD, total_duration = TFT, go_past_time = RPD_inc, len = word_length, prev_len = word_length_word_n_minus_1, freq = lex_freq, prev_freq = lex_freq_word_n_minus_1, surp = surprisal, prev_surp = surprisal_word_n_minus_1) %>%
  gather(key = "measures", value = "value", all_of(measures_col)) %>%
  group_by(measures) %>%
  mutate(mean = mean(value, na.rm = TRUE),
         sd = sd(value, na.rm = TRUE)) %>%
  filter((measures %in% c("FPReg", "skip", "FPSkip")) | value <= (mean + 5 * sd)) %>%
  ungroup() %>%
  dplyr::select(-mean, -sd) %>%
  mutate(
    subj_id = as.integer(factor(subj)),
    c1 = ifelse(session_label == "ET1", 1, 0),
    c2 = ifelse(session_label == "ET2", 1, 0)
    ) %>%
  drop_na()

# View(et_indico)
# 
# write_csv(et_indico, "../data/fit_input/et_indico.csv")
```

```{r Model InDiCo Data}
priors_rt <- c(
  prior(normal(5.5, 0.1), class = Intercept),
  prior(normal(0, 0.1), class = b),
  prior(exponential(2), class = sd),
  prior(exponential(2), class = sigma),
  prior(lkj(1), class = cor)
)

for(mes in c("gaze_duration")) {
  print(paste0("Fitting model for ", mes))
  
  temp_df <- et_indico %>%
    filter(measures == mes) %>%
    filter(value > 0)
  
  # Fit the model for RT measures
  model <- brms::brm(
    value ~ 1 + c2 + len + freq + surp + prev_len + prev_freq + prev_surp + 
    (0 + c1 + c2 + (len + freq + surp + prev_len + prev_freq + prev_surp):c1 + (len + freq + surp + prev_len + prev_freq + prev_surp):c2 | subj_id),
    data = temp_df,
    chains = 4,
    family = lognormal(),
    warmup = 1000,
    iter = 2000,
    file = paste0("../models/cor_scaled/", "indicos_", mes),
    cores = 4,
    backend = "rstan",
    silent = 0,
    prior = priors_rt
  )
}

print("Done fitting models")
```

