---
title: "meta analysis"
output: html_document
date: "2026-07-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list=ls())
```

```{r Libraries, warning=FALSE, message=FALSE}
# Set locale to English
Sys.setlocale("LC_ALL", "en_US.UTF-8")

#!/usr/bin/env Rscript
library(ggplot2)
library(boot)
library(readr)
library(tidyr)
library(dplyr)
library(tibble)
library(stringr)
library(readr)
library(gridExtra)
library(lme4)
library(lmerTest)
library(MASS)
library(brms)
library(rstan)
library(cmdstanr)
```

```{r}
indico <- read_csv("../data/fit_input/et_indico.csv") %>% 
  filter(measures == "gaze_duration", value > 0) %>%
  dplyr::select(-trial, -session_label, -subj_id) %>%
  mutate(corpus = ifelse(c1==1, "indicos1", "indicos2"), text_id = paste0("indico_", text_id)) 
# View(indico)

potec <- read_csv("../data/fit_input/potec.csv") %>% 
  filter(measures == "gaze_duration", value > 0) %>%
  dplyr::select(-trial, -text_domain, -reader_discipline, -subj_id) %>%
  mutate(corpus = ifelse(c1==1, "potecin", "potecout"), 
         text_id = paste0("potec_", sub("^t", "", text)),
         subj = paste0("ptc", sub("^s", "", subj))) %>% dplyr::select(-text)
# View(potec)

onestop <- read_csv("../data/fit_input/onestop.csv") %>%
  filter(measures == "gaze_duration", value > 0) %>%
  dplyr::select(-trial, -paragraph, -repeated_reading_trial, -repeated, -subj) %>%
  mutate(corpus = ifelse(c1==1, "onestopre", "onestopno"), 
         text_id = paste0("onestop_", sub("^t", "", text)),
         subj = paste0("ost", subj_id)) %>% dplyr::select(-text, -subj_id)
  
# View(onestop)

geconl <- read_csv("../data/fit_input/geconl.csv") %>%
  filter(measures == "gaze_duration", value > 0) %>%
  dplyr::select(-trial, -lang) %>%
  mutate(corpus = ifelse(c1==1, "geconll1", "geconll2"), 
         text_id = paste0("geconl_", part),
         subj = paste0("gnl", subj_id)) %>% dplyr::select(-part, -subj_id)

# View(geconl)

gecozh <- read_csv("../data/fit_input/gecozh.csv") %>%
  filter(measures == "gaze_duration", value > 0) %>%
  dplyr::select(-trial, -lang) %>%
  mutate(corpus = ifelse(c1==1, "gecozhl1", "gecozhl2"),
         text_id = paste0("gecozh_", part),
         subj = paste0("gzh", subj_id)) %>% dplyr::select(-part, -subj_id)

# View(gecozh)

hkc <- read_csv("../data/fit_input/hkc.csv") %>%
  filter(measures == "gaze_duration", value > 0) %>%
  dplyr::select(-subj) %>%
  mutate(corpus = ifelse(c1==1, "hkcpara", "hkcsent"),
         text_id = paste0("hkc", sub("^t", "", text)),
         subj = paste0("hkc", subj_id)) %>% dplyr::select(-subj_id, -text, -trial, -format)

# View(hkc)

meta <- bind_rows(indico, potec, onestop, geconl, gecozh, hkc) %>%
  mutate(corpus = factor(corpus, levels = c("indicos1", "indicos2", "potecin", "potecout", "onestopre", "onestopno", "geconll1", "geconll2", "gecozhl1", "gecozhl2", "hkcpara", "hkcsent")))

View(meta)
```

```{r}
contrasts(meta$corpus) <- contr.sum(nlevels(meta$corpus))
levels(meta$corpus)
contrasts(meta$corpus)
```

```{r eval=FALSE}
priors_rt <- c(
  prior(normal(5.1, 0.1), class = Intercept),
  prior(normal(0, 0.1), class = b),
  prior(exponential(5), class = sd),
  prior(exponential(5), class = sigma)
  # prior(lkj(1), class = cor)
)

  
# Fit the model for RT measures
model <- brms::brm(
  value ~ 1 + len + freq + surp + prev_len + prev_freq + prev_surp + (1 | subj) + (1 | corpus),
  data = meta,
  chains = 4,
  family = lognormal(link = "identity"),
  warmup = 1000,
  iter = 2000,
  file = paste0("../models/meta/", "meta_", mes),
  cores = 4,
  backend = "cmdstan",
  silent = 0,
  prior = priors_rt
)

print("Done fitting models")
```

```{r}
m.meta <- read_rds("../models/meta/meta_gaze_duration.rds")
fe_table <- fixef(m.meta, probs = c(0.025, 0.975)) %>%
  as.data.frame() %>%
  rownames_to_column("Predictor") %>%
  rename(
    Estimate = Estimate,
    SE = Est.Error,
    CI_lower = Q2.5,
    CI_upper = Q97.5
  ) %>%
  mutate(
    across(where(is.numeric), \(x) round(x, 5))
  )

fe_table
```

