---
title: "noise_table_creation"
output: html_document
date: "2025-08-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Libraries, warning=FALSE, message=FALSE}
# Set locale to English
Sys.setlocale("LC_ALL", "en_US.UTF-8")

#!/usr/bin/env Rscript
library(ggplot2)
library(boot)
library(readr)
library(tidyr)
library(dplyr)
library(purrr)
library(gridExtra)
library(lme4)
library(lmerTest)
library(glmmTMB)
library(MASS)
library(brms)
library(mirt)
library(gtable)
library(cowplot)
library(grid)
library(ggdist)
library(RColorBrewer)
library(colorspace)

# Helper function
get_response_type <- function(name) {
  if (grepl("FPRT|TFT|FFD|RPD|SPR", name)) {
    return("1_continuous")
  } else if (grepl("SKIP|FPReg", name)) {
    return("2_binary")
  } else if (grepl("N_FIX", name)) {
    return("3_count")
  }
}
```


```{r overviewtab, warning=FALSE}
# Load libraries
# Updated predictors including spillover
predictors_rao <- c(
  "sd(s1)",
  "sd(s2)",
  "sd(s2:word_length)",
  "sd(s2:lex_freq)",
  "sd(s2:surprisal)",
  "sd(s2:dep_distance)",
  "sd(s2:n_lefts)",
  "sd(s2:word_length_word_n_minus_1)",
  "sd(s2:lex_freq_word_n_minus_1)",
  "sd(s2:surprisal_word_n_minus_1)",
  "sd(s2:dep_distance_word_n_minus_1)",
  "sd(s2:n_lefts_word_n_minus_1)"
)



# Read all RAO models
model_prefix <- "./results/final_rao/"
fnames <- list.files(model_prefix, pattern = "^rao")
print(fnames)

noise_df <- data.frame()
for (f in fnames) {
  m <- read_rds(file.path(model_prefix, f))
  sum_m <- summary(m)
  sigma <- sum_m$spec_pars[1, "Estimate"]
  randeffs <- sum_m$random$subj_id
  nobs <- sum_m$nobs
  nind <- sum_m$ngrps$subj_id
  measure_name <- substr(f, 15, nchar(f) - 4)
  response_type <- get_response_type(measure_name)

  ests <- data.frame(estimate = randeffs[predictors_rao, "Estimate"])
  ests$parameter <- predictors_rao
  ests$parameter <- gsub(":", "_", ests$parameter)
  ests$parameter <- gsub("\\(", "_", ests$parameter)
  ests$parameter <- gsub("\\)", "", ests$parameter)
  ests_wide <- spread(ests, key = parameter, value = estimate)
  ests_wide$measure <- measure_name
  ests_wide$type <- "1_rao"
  ests_wide$response_type <- response_type
  ests_wide$sigma <- sigma
  ests_wide$nobs <- nobs
  ests_wide$nind <- nind
  noise_df <- bind_rows(noise_df, ests_wide)
}

# Keep continuous RAO only
noise_df <- noise_df %>%
  filter(type == "1_rao", response_type == "1_continuous") %>%
  mutate(
    across(starts_with("sd_"), ~ .x / sigma, .names = "eta_{.col}")
  )

# Round all numeric values
noise_df <- noise_df %>%
  mutate(across(where(is.numeric), ~ round(., 2)))

# Helper to remove leading 0
remove_leading_zero <- function(x) {
  sub("^0\\.", ".", sprintf("%.2f", x))
}

# Function to get local + spillover gamma
make_gamma_row <- function(row, base) {
  local_col <- paste0("eta_sd_s2_", base)
  spill_col <- paste0("eta_sd_s2_", base, "_word_n_minus_1")
  local_val <- ifelse(local_col %in% names(row), remove_leading_zero(row[[local_col]]), "")
  spill_val <- ifelse(spill_col %in% names(row), remove_leading_zero(row[[spill_col]]), "")
  return(c(local_val, spill_val))
}

# Build LaTeX table
latex_table <- "\\begin{table}[h]
\\centering
\\begin{tabular}{l|rr|r|cc|cc|cc|cc|cc}
\\toprule
\\multirow{2}{*}{Measure} & \\multirow{2}{*}{$n_{obs}$} & \\multirow{2}{*}{$n_{ind}$} & \\multirow{2}{*}{$\\hat{\\sigma}$} & \\multicolumn{2}{c}{$\\gamma_{wl}$} & \\multicolumn{2}{c}{$\\gamma_{f}$} & \\multicolumn{2}{c}{$\\gamma_{s}$} & \\multicolumn{2}{c}{$\\gamma_{d}$} & \\multicolumn{2}{c}{$\\gamma_{nl}$} \\\\
& & & & local & spill & local & spill & local & spill & local & spill & local & spill \\\\
\\midrule
"

for (i in 1:nrow(noise_df)) {
  row <- noise_df[i, ]
  wl <- make_gamma_row(row, "word_length")
  f  <- make_gamma_row(row, "lex_freq")
  s  <- make_gamma_row(row, "surprisal")
  d  <- make_gamma_row(row, "dep_distance")
  nl <- make_gamma_row(row, "n_lefts")

  latex_table <- paste0(
    latex_table,
    sprintf("%s & %d & %d & %s & %s & %s & %s & %s & %s & %s & %s & %s & %s & %s \\\\\n",
      row$measure, row$nobs, row$nind, remove_leading_zero(row$sigma),
      wl[1], wl[2], f[1], f[2], s[1], s[2], d[1], d[2], nl[1], nl[2]
    )
  )
}

latex_table <- paste0(latex_table, "\\bottomrule
\\end{tabular}
\\caption{Trial-by-trial dispersion ($\\hat{\\sigma}$) and normalized between-participant variance ($\\gamma$) of local and spillover effects (RAO models only).}
\\label{tab:noise_params_spill}
\\end{table}
")

writeLines(latex_table, "results/stats/noise_params_spill_table_appendix_s2.tex")

```
